# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Common/Projects/git/odfi-manager/install/rfg3/examples/boards/nexys/NexysDemo.cache/wt [current_project]
set_property parent.project_path E:/Common/Projects/git/odfi-manager/install/rfg3/examples/boards/nexys/NexysDemo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib E:/Common/Projects/git/odfi-manager/install/rfg3/examples/boards/nexys/NexysDemo.srcs/sources_1/new/nexys_demo_top.v
read_xdc E:/Common/Projects/git/odfi-manager/install/rfg3/examples/boards/nexys/constraints/nexys_demo.xdc
set_property used_in_implementation false [get_files E:/Common/Projects/git/odfi-manager/install/rfg3/examples/boards/nexys/constraints/nexys_demo.xdc]

synth_design -top nexys_demo_top -part xc7a200tsbg484-1
write_checkpoint -noxdef nexys_demo_top.dcp
catch { report_utilization -file nexys_demo_top_utilization_synth.rpt -pb nexys_demo_top_utilization_synth.pb }
