#define RFG_INFO_SCRATCHPAD0 0x0
#define RFG_INFO_SCRATCHPAD1 0x1
#define RFG_INFO_TEST_FIFO 0x2
#define RFG_INFO_TEST_FIFO2 0x3
#define RFG_INFO_TEST_FIFO2_STATUS 0x4
#define RFG_INFO_TEST_FIFO2_STATUS 0x5
